"""项目级默认配置。"""

DEFAULT_BROWSER_NAME = "douyin_creator"
DEFAULT_CREATOR_URL = "https://creator.douyin.com/"
DEFAULT_CHAT_URL = "https://creator.douyin.com/creator-micro/data/following/chat"
DEFAULT_OUTPUT_DIR = "chat_messages_output"
DEFAULT_LOGIN_TIMEOUT = 300

DEFAULT_BROWSER_REMARK = "抖音创作者中心专用窗口"
DEFAULT_BROWSER_FINGERPRINT = {
    "coreVersion": "130",
    "ostype": "PC",
    "os": "Win32",
    "osVersion": "11,10",
}

DEFAULT_MONITOR_INTERVAL_SECONDS = 15
DEFAULT_COOLDOWN_SECONDS = 300
DEFAULT_DAILY_LIMIT = 50
DEFAULT_WORK_START = "09:00"
DEFAULT_WORK_END = "22:00"
DEFAULT_REPLY_MAX_RETRIES = 2
DEFAULT_REPLY_MAX_CHARS = 300
DEFAULT_CONTEXT_MAX_CHARS = 2000
DEFAULT_MEMORY_MESSAGE_LIMIT = 10

DEFAULT_AI_BASE_URL = "https://api.openai.com/v1"
DEFAULT_AI_MODEL = "gpt-4.1-mini"
DEFAULT_AI_TEMPERATURE = 0.7
DEFAULT_AI_MAX_TOKENS = 400
DEFAULT_AI_TIMEOUT_SECONDS = 60

APP_ORGANIZATION_NAME = "CodexLocal"
APP_APPLICATION_NAME = "DouyinAutoReply"
